### PR TITLE
First pass to split the generation 

### PR DESCRIPTION
**Pull request by yakovkhalinsky**
Things done in this PR:

- [x]  Implement base configuration in `droid.config.js`
- [x]  Split patch generation into header, sequencers and footer modules
- [x]  Update README

### CODE REVIEW

**Comment by yakovkhalinsky** [comment]
I want to update the README before this gets merged

**Comment by yakovkhalinsky** [comment]
@tomhazledine have updated the README to reflect the changes 👍

**Comment by tomhazledine** [comment]
I really like the addition of a config object. It makes this much more flexible 👍 

One aspect of the original setup I was quite happy with was that there was "no installation required", so I'm a little resistant to adding `mustache` as a dependency... *but* I do like having an easy way to override the ins/out/controls, and can't immediately think of a better (dep-free) way of doing it. I'll think about the options for a little bit (maybe inspiration will strike after I've had more coffee) but if I can't think of an alternative by tomorrow morning then we can merge this as-is.

Great work

**Comment by yakovkhalinsky** [comment]
> 

Yeah I totally understand, might look at wrapping this in an electron app or something that is a single download because I agree with that as a user friendly thing to do

**Review by tomhazledine — APPROVED** [review]

**Pull request merged**
